[workspace]
members = [
    "crates/steg-img-encode",
    "crates/steg-img-decode",
    "crates/steg-img-write",
    "crates/steg-fs-driver",
    "crates/steg-fs-mgmt",
    "crates/steg-compress",
    "crates/steg-fs-ui",
    "crates/steg-fs-app",
]