[package]
name = "steg-img-encode"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"   # For image manipulation
base64 = "0.21"  # For base64 encoding/decoding
aes-gcm = "0.10" # For encryption
rand = "0.8"     # For generating encryption keys